name: 3D + Metrics

on:
  schedule:
    - cron: "0 6 * * *"     # 03:00 BRT
  workflow_dispatch:

permissions:
  contents: write

jobs:
  contrib-3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit 3‑D
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/*.svg
          git diff --cached --quiet || { git commit -m "chore: update 3‑D graph"; git push; }

  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-private.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_languages: yes
          plugin_lines: yes
          plugin_languages_limit: 10
          config_timezone: America/Sao_Paulo
      - name: Commit Metrics
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add metrics-private.svg
          git diff --cached --quiet || { git commit -m "chore: update metrics"; git push; }
